### ISSUE TITLE
BSP having trouble with OP Commands

### ISSUE THREAD

**Issue by maegae** [Blackixx/BossShopPro#48]
Hi, I'm using BossShopPro in my 1.15.1 server, and many of the gui's I have created from previous versions that worked well before don't work so well now, and same with gui's I've just created. I've figured out that the main issue I'm having is with OP commands.

Clicking on an item that's meant to execute an OP command will lag the server, execute the command, but still abide by the player permissions. Here's an example of an item I have:
```
  bflame:
    MenuItem:
    - 'name:&5&lBurning Flame | 3 Gems'
    - amount:1
    - type:blaze_powder
    RewardType: opcommand
    Reward:
    - metake %player% gems 3
    - lp user %player% permission set pp.bflame true
    Condition:
    - type:placeholdernumber
    - '%multieconomy_amount_gems%:over:2'
    InventoryLocation: 10
```
What I want this to do, is take the gems, given the player has enough gems to purchase it, and then give them this permission (I've tried using external addons such as ThirdCurrency to add a pricetype to this so I can just have the reward be the "permission" type, but with no luck). However, what really happens, is it takes the gems, then says "You do not have permission to use this command".
![image](https://user-images.githubusercontent.com/46981076/72540771-3b26a800-3836-11ea-83bf-782903fa4450.png)

Is this a bug because I'm using BSP in 1.15.1, or did I set something up wrong, or is it another issue entirely?
