### ISSUE TITLE
Dyed armor not working

### ISSUE THREAD

**Issue by B4m1237** [Blackixx/BossShopPro#62]
I'm trying to make a leather armor menu item colored in the menu. I'm following the instructions from the item data information page. https://www.spigotmc.org/wiki/bossshoppro-itemdata/

I've also tried using /bs read ingame on the item to get the type & color.

The issue is the same both with the bs read generated data, and following the instructions in the item data page. The first hashtag turns the second color and everything past it, into a comment. This causes the leather armor to remain plain brown armor in the menu. I've used the hashtag with enchants and hideflags and never had the issue, it only happens with the color: no matter what I try. I've included my item & the bs generated item below.

```
  Golden:
    MenuItem:
    - name:&6&lLeather Armor
    - 'lore1:&7Don''t want to die?'
    - 'lore2:&7Buy this horribly priced leather armor!'
    - 'lore3:&7Protection 4, Unbreaking 4, & Mending'
    - 'lore5:&7Cost: &e$600'
    - amount:1
    - type:LEATHER_CHESTPLATE
    - color:255#196#0
    Condition:
    - type:permission
    - match:essentials.kits.clagol
    RewardType: playercommand
    Reward:
    - kit clagol
    PriceType: NOTHING
    Message: ''
    ExtraPermission: ''
    InventoryLocation: 4


  2020 17-05 at 02:33:48 AM (Sun):
  - type:LEATHER_CHESTPLATE
  - amount:1
  - durability:0
  - name:&6Golden Chestplate
  - enchantment:mending#1
  - enchantment:protection#5
  - enchantment:unbreaking#4
  - color:255#196#0
```
