### ISSUE TITLE
Item META and NBT MUST be used!

### ISSUE THREAD

**Issue by mrcoffee1026** [Blackixx/BossShopPro#87]
This plugin is NOT 1.15+ ready as it is still not complying with items as they have been updated in that version.  As an example here is a perfectly formed item as stored by the plugin CratesPlus which actually can still accurately match custom items and items from other plugins:
```
      '14':
        Type: ITEM
        Item Type: FIREWORK_STAR
        Item Data: 0
        Name: '&7Ancient Rune &8&l[&5&lSoulbound&8&l]'
        Amount: 8
        Enchantments: []
        Lore:
        - §eDrop this rune onto a dropped item to
        - §5bind §ethat item to your soul.
        - ' '
        - §eIt is advised that you only use this rune
        - §eon §6important §eitems.
        - ' '
        - §eItems bound to your soul won't drop on death.
        Metadata:
          ==: ItemMeta
          meta-type: FIREWORK_EFFECT
          display-name: §7Ancient Rune §8§l[§5§lSoulbound§8§l]
          lore:
          - §eDrop this rune onto a dropped item to
          - §5bind §ethat item to your soul.
          - ' '
          - §eIt is advised that you only use this rune
          - §eon §6important §eitems.
          - ' '
          - §eItems bound to your soul won't drop on death.
          PublicBukkitValues:
            slimefun:slimefun_item: ANCIENT_RUNE_SOULBOUND
          firework-effect:
            ==: Firework
            flicker: false
            trail: false
            colors:
            - ==: Color
              RED: 47
              BLUE: 117
              GREEN: 0
            fade-colors: &id001 []
            type: BURST

```

Here is that same item as seen by BossShopPro's /bs read command:
```
  2020 26-09 at 03:04:18 PM (Sat):
  - type:FIREWORK_STAR
  - amount:4
  - durability:0
  - name:&7Ancient Rune &8&l[&5&lSoulbound&8&l]
  - lore1:&eDrop this rune onto a dropped item to
  - lore2:&5bind &ethat item to your soul.
  - 'lore3: '
  - lore4:&eIt is advised that you only use this rune
  - lore5:&eon &6important &eitems.
  - 'lore6: '
  - lore7:&eItems bound to your soul won't drop on death.
```
The discrepancies should be obvious, but the bottom line is the BossShop version of this item does not function and can not be properly used to match the appropriate item even when it already exists.  Please address this issue ASAP.

BossShop Pro v2.0.9
Paper - 204
